"""Unit tests for multimodal resource generators (Phase 3.9).

Verifies:
  - PPTXGenerator produces valid PPTX bytes with correct slide count
  - CodeZIPGenerator produces valid ZIP with security checks
  - InteractiveGenerator produces valid cards, walkthrough, and simulation
  - All generators handle empty/minimal input gracefully

Run with:
    pytest tests/unit/test_multimodal_generators.py -v
"""

from __future__ import annotations

import zipfile
from io import BytesIO

import pytest

from app.services.code_generator import CodeZIPGenerator
from app.services.interactive_generator import InteractiveGenerator
from app.services.pptx_generator import PPTXGenerator


# ──────────────────────────────────────────────
# Test data
# ──────────────────────────────────────────────

SAMPLE_UNIT_CONTENT = {
    "introduction": "# Python 基础语法\n\n本节介绍 Python 的基本语法。",
    "objectives": ["理解变量和类型", "掌握基本运算符", "学会使用条件语句"],
    "sections": [
        {
            "section_id": "s1",
            "title": "变量与类型",
            "content": "Python 中的变量不需要声明类型。\n整数、浮点数、字符串是基本类型。\n使用 type() 查看变量类型。",
            "order": 1,
        },
        {
            "section_id": "s2",
            "title": "运算符",
            "content": "算术运算符：+、-、*、/\n比较运算符：==、!=、>、<\n逻辑运算符：and、or、not",
            "order": 2,
        },
        {
            "section_id": "s3",
            "title": "条件语句",
            "content": "if 语句用于条件判断。\nif-else 用于二选一分支。\nif-elif-else 用于多分支。",
            "order": 3,
        },
    ],
    "practice_tasks": [
        {"description": "定义两个变量并交换它们的值"},
        {"description": "使用 if-else 判断成绩等级"},
    ],
    "summary": "本节学习了 Python 的变量、运算符和条件语句，这些是编程的基础。",
    "key_terms": [
        {"term": "变量", "definition": "存储数据的命名容器"},
        {"term": "运算符", "definition": "执行运算的符号"},
    ],
}


MINIMAL_UNIT_CONTENT = {
    "introduction": "测试内容",
    "objectives": [],
    "sections": [],
    "practice_tasks": [],
    "summary": "",
}


# ──────────────────────────────────────────────
# PPTX Generator Tests
# ──────────────────────────────────────────────


class TestPPTXGenerator:
    """Verify PPTX generation from unit content."""

    def test_generate_pptx_bytes_returns_valid_pptx(self):
        """Generated bytes should be a valid PPTX file."""
        pptx_bytes = PPTXGenerator.generate_pptx_bytes(SAMPLE_UNIT_CONTENT)

        if pptx_bytes is None:
            pytest.skip("python-pptx not installed")

        assert len(pptx_bytes) > 0

        # Verify it's a valid PPTX (ZIP-based format)
        import zipfile

        with zipfile.ZipFile(BytesIO(pptx_bytes)) as zf:
            assert "ppt/presentation.xml" in zf.namelist()

    def test_generate_pptx_has_correct_slide_count(self):
        """PPTX should have slides for title, objectives, sections, tasks, and summary."""
        pptx_bytes = PPTXGenerator.generate_pptx_bytes(SAMPLE_UNIT_CONTENT)

        if pptx_bytes is None:
            pytest.skip("python-pptx not installed")

        from pptx import Presentation

        prs = Presentation(BytesIO(pptx_bytes))
        # Title + Objectives + 3 sections (each short enough for 1 slide) + Practice + Summary = 7
        assert len(prs.slides) >= 5

    def test_generate_pptx_with_minimal_content(self):
        """PPTX generation should work with minimal content."""
        pptx_bytes = PPTXGenerator.generate_pptx_bytes(MINIMAL_UNIT_CONTENT)

        if pptx_bytes is None:
            pytest.skip("python-pptx not installed")

        assert len(pptx_bytes) > 0
        from pptx import Presentation

        prs = Presentation(BytesIO(pptx_bytes))
        # At least a title slide
        assert len(prs.slides) >= 1

    def test_generate_pptx_title_matches_content(self):
        """The first slide title should come from the introduction."""
        pptx_bytes = PPTXGenerator.generate_pptx_bytes(SAMPLE_UNIT_CONTENT)

        if pptx_bytes is None:
            pytest.skip("python-pptx not installed")

        from pptx import Presentation

        prs = Presentation(BytesIO(pptx_bytes))
        first_slide = prs.slides[0]
        title_text = ""
        for shape in first_slide.shapes:
            if shape.has_text_frame:
                title_text = shape.text_frame.text
                break
        assert "Python" in title_text or "基础语法" in title_text


# ──────────────────────────────────────────────
# Code ZIP Generator Tests
# ──────────────────────────────────────────────


class TestCodeZIPGenerator:
    """Verify code ZIP generation with security checks."""

    def test_generate_zip_returns_valid_zip(self):
        """Generated bytes should be a valid ZIP file."""
        zip_bytes, file_list = CodeZIPGenerator.generate_zip_bytes(SAMPLE_UNIT_CONTENT)

        assert len(zip_bytes) > 0
        assert len(file_list) > 0
        assert "README.md" in file_list

        with zipfile.ZipFile(BytesIO(zip_bytes)) as zf:
            assert "README.md" in zf.namelist()

    def test_zip_contains_readme_with_content(self):
        """README.md should contain project description."""
        zip_bytes, _ = CodeZIPGenerator.generate_zip_bytes(SAMPLE_UNIT_CONTENT)

        with zipfile.ZipFile(BytesIO(zip_bytes)) as zf:
            readme = zf.read("README.md").decode("utf-8")
            assert "Python" in readme or "python" in readme.lower()
            assert "学习目标" in readme
            assert "运行方式" in readme

    def test_zip_contains_example_code_file(self):
        """ZIP should contain at least one example code file."""
        zip_bytes, file_list = CodeZIPGenerator.generate_zip_bytes(SAMPLE_UNIT_CONTENT)

        code_files = [f for f in file_list if f.endswith((".py", ".js"))]
        assert len(code_files) > 0

    def test_zip_does_not_contain_forbidden_extensions(self):
        """ZIP should not contain .sh, .bat, .exe, etc."""
        forbidden = {".sh", ".bat", ".cmd", ".ps1", ".exe", ".dll"}
        _, file_list = CodeZIPGenerator.generate_zip_bytes(SAMPLE_UNIT_CONTENT)

        for filename in file_list:
            ext = "." + filename.rsplit(".", 1)[-1] if "." in filename else ""
            assert ext.lower() not in forbidden, f"Forbidden extension: {filename}"

    def test_zip_respects_max_size(self):
        """ZIP should not exceed maximum size limit."""
        zip_bytes, _ = CodeZIPGenerator.generate_zip_bytes(SAMPLE_UNIT_CONTENT)

        assert len(zip_bytes) <= 500_000  # 500 KB max

    def test_zip_with_minimal_content(self):
        """ZIP generation should work with minimal content."""
        zip_bytes, file_list = CodeZIPGenerator.generate_zip_bytes(MINIMAL_UNIT_CONTENT)

        assert len(zip_bytes) > 0
        assert "README.md" in file_list

    def test_security_check_detects_forbidden_patterns(self):
        """The security check should detect forbidden patterns."""
        assert CodeZIPGenerator._contains_forbidden_patterns("rm -rf /")
        assert CodeZIPGenerator._contains_forbidden_patterns("subprocess.call('evil')")
        assert CodeZIPGenerator._contains_forbidden_patterns("eval('malicious')")
        assert not CodeZIPGenerator._contains_forbidden_patterns("print('hello')")
        assert not CodeZIPGenerator._contains_forbidden_patterns("def main():")


# ──────────────────────────────────────────────
# Interactive Generator Tests
# ──────────────────────────────────────────────


class TestInteractiveCardsGenerator:
    """Verify interactive cards generation."""

    def test_generate_cards_returns_valid_structure(self):
        """Generated cards should have correct structure."""
        result = InteractiveGenerator.generate_cards(SAMPLE_UNIT_CONTENT)

        assert result["interactive_type"] == "cards"
        assert "title" in result
        assert "description" in result
        assert "items" in result
        assert "knowledge_points" in result
        assert "estimated_minutes" in result
        assert isinstance(result["items"], list)
        assert len(result["items"]) > 0

    def test_cards_have_front_back_and_hint(self):
        """Each card should have front, back, and hint fields."""
        result = InteractiveGenerator.generate_cards(SAMPLE_UNIT_CONTENT)

        for card in result["items"]:
            assert "front" in card
            assert "back" in card
            assert "hint" in card
            assert "knowledge_point" in card
            assert "difficulty" in card
            assert card["difficulty"] in ("easy", "medium", "hard")

    def test_cards_include_objectives_and_key_terms(self):
        """Cards should include items from objectives and key terms."""
        result = InteractiveGenerator.generate_cards(SAMPLE_UNIT_CONTENT)

        # 3 objectives + 2 key terms + at least 1 section card + 2 practice + 1 summary
        assert len(result["items"]) >= 5

    def test_cards_with_minimal_content(self):
        """Cards generation should work with minimal content."""
        result = InteractiveGenerator.generate_cards(MINIMAL_UNIT_CONTENT)

        assert result["interactive_type"] == "cards"
        # Should at least have a title-based card or empty items
        assert "items" in result

    def test_estimated_minutes_is_positive(self):
        """Estimated minutes should be at least 5."""
        result = InteractiveGenerator.generate_cards(SAMPLE_UNIT_CONTENT)

        assert result["estimated_minutes"] >= 5


class TestWalkthroughGenerator:
    """Verify walkthrough generation."""

    def test_generate_walkthrough_returns_valid_structure(self):
        """Generated walkthrough should have correct structure."""
        result = InteractiveGenerator.generate_walkthrough(SAMPLE_UNIT_CONTENT)

        assert result["interactive_type"] == "walkthrough"
        assert "title" in result
        assert "description" in result
        assert "items" in result
        assert isinstance(result["items"], list)
        assert len(result["items"]) > 0

    def test_walkthrough_items_have_step_and_question(self):
        """Each walkthrough item should have step, title, question, and expected_answer."""
        result = InteractiveGenerator.generate_walkthrough(SAMPLE_UNIT_CONTENT)

        for item in result["items"]:
            assert "step" in item
            assert "title" in item
            assert "description" in item
            assert "question" in item
            assert "expected_answer" in item

    def test_walkthrough_steps_are_sequential(self):
        """Walkthrough steps should be numbered sequentially."""
        result = InteractiveGenerator.generate_walkthrough(SAMPLE_UNIT_CONTENT)

        steps = [item["step"] for item in result["items"]]
        assert steps == list(range(1, len(steps) + 1))

    def test_walkthrough_with_minimal_content(self):
        """Walkthrough generation should work with minimal content."""
        result = InteractiveGenerator.generate_walkthrough(MINIMAL_UNIT_CONTENT)

        assert result["interactive_type"] == "walkthrough"


class TestSimulationGenerator:
    """Verify simulation generation."""

    def test_generate_simulation_returns_valid_structure(self):
        """Generated simulation should have correct structure."""
        result = InteractiveGenerator.generate_simulation(SAMPLE_UNIT_CONTENT)

        assert result["interactive_type"] == "simulation"
        assert "title" in result
        assert "description" in result
        assert "items" in result
        assert isinstance(result["items"], list)
        assert len(result["items"]) > 0

    def test_simulation_items_have_label_and_state(self):
        """Each simulation item should have label, state, and description."""
        result = InteractiveGenerator.generate_simulation(SAMPLE_UNIT_CONTENT)

        for item in result["items"]:
            assert "label" in item
            assert "state" in item
            assert isinstance(item["state"], dict)

    def test_simulation_starts_with_initial_state(self):
        """First simulation item should be the initial state."""
        result = InteractiveGenerator.generate_simulation(SAMPLE_UNIT_CONTENT)

        first = result["items"][0]
        assert "初始" in first["label"] or "开始" in first["label"]

    def test_simulation_ends_with_final_state(self):
        """Last simulation item should be the final state."""
        result = InteractiveGenerator.generate_simulation(SAMPLE_UNIT_CONTENT)

        last = result["items"][-1]
        assert "完成" in last["label"] or "最终" in last["label"]

    def test_simulation_mastery_progresses(self):
        """Mastery should increase from 0 to 100."""
        result = InteractiveGenerator.generate_simulation(SAMPLE_UNIT_CONTENT)

        masteries = [
            item["state"].get("mastery", 0)
            for item in result["items"]
            if "mastery" in item["state"]
        ]
        if len(masteries) >= 2:
            assert masteries[0] <= masteries[-1]
            assert masteries[-1] == 100.0

    def test_simulation_with_minimal_content(self):
        """Simulation generation should work with minimal content."""
        result = InteractiveGenerator.generate_simulation(MINIMAL_UNIT_CONTENT)

        assert result["interactive_type"] == "simulation"
